### ISSUE TITLE
Can't add more than 6 themes per switcher

### ISSUE THREAD

**Issue by Imageburst** [ZeroWP/demonstrator#1]
It appears that there's a limit of how many demos you can show in a switcher. I've added 12 to single switcher and only 6 appears. Even adjusting the layout to show 4 columns/grids, it still didn't appear.

**Comment by awps** [comment]
Hi.

I just tested it and it's all OK. You probably forgot to add at the demo URL:
![ashampoo_snap_2018 04 07_23h07m03s_002_](https://user-images.githubusercontent.com/1436534/38459913-ad4ef298-3ab8-11e8-8c1e-8f58c13cdd23.png)

Let me know if this is the case.
Thank you.

**Comment by awps** [comment]
@Imageburst , can you confirm if this was the problem? 
Thank you.
