### ISSUE TITLE
Uneven Thumbnails

### ISSUE THREAD

**Issue by Imageburst** [ZeroWP/demonstrator#2]
When you upload a thumbnail that doesn't match the exact width and height of this plugins suggestion dimensions, you get empty areas with a border around it.  Could there be a better way to show thumbnails that have different height and width? Like auto width and height?

**Comment by awps** [comment]
Hi.

I added an option in version 1.3.0 called "Image Aspect Ratio". Select anything except "auto". 😉

![screenshot_2018 07 05_15h34m35s_002_](https://user-images.githubusercontent.com/1436534/42323568-4f665882-8069-11e8-83e3-9692304ebc17.jpg)
